### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by alessandroDeIturbe** [cinuor/nvim#7]
Just for know, how do you uninstall these?

**Comment by LowGasPay** [comment]
rm -rf ~/.local/share/nvim

**Comment by doodleEsc** [comment]
> rm -rf ~/.local/share/nvim

and also remove `compiled.lua` file in ~/.config/nvim/lua/doodleVim/

**Comment by alessandroDeIturbe** [comment]
Thanks!
